# Configuration file for https://github.com/apps/settings.
# See also: https://github.com/brave/internal/wiki/Pull-request-security-audit-checklist#github-repository-security.

# https://docs.github.com/en/rest/reference/repos#update-a-repository
repository:
  #name:
  #description:
  #homepage:
  #topics:
  private: true
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: bug
    color: CC0000
    description: An issue with the system
  - name: security
    color: C215F2
    description: A security issue

#milestones:
#  - title: milestone-title
#    description: milestone-description
#    state: open

# https://docs.github.com/en/rest/reference/repos#add-a-repository-collaborator (permissions: pull, push, triage, maintain, admin)
collaborators:
  - username: brave-security-bot
    permission: pull

# Commented out due to: https://github.com/brave/support/issues/3887#issuecomment-1323840517.
# https://docs.github.com/en/rest/reference/teams#add-or-update-team-repository-permissions (permissions: pull, push, triage, maintain, admin)
#teams:
#  - name: brave/it-support-team
#    permission: admin

branches:
  - name: main
    # https://docs.github.com/en/rest/reference/repos#update-branch-protection
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: false
        contexts: [] # list of required checks
      enforce_admins: true
      required_linear_history: false
      restrictions:
        apps: []
        users: []
        teams: []

